title: Gene Ishchuk
logo: /assets/img/IMG2.png
description: Product Manager with AdTech & Web Analytics experience (5+ years).
Certified Scrum Master (PSM I) and mentor on MentorCruise.
show_downloads: false
theme: jekyll-theme-minimal